spring.application.name=class
spring.datasource.url=jdbc:postgresql://localhost:5432/laboratorio
spring.datasource.username=postgres
spring.datasource.password=Diegoa01.

spring.jpa.hibernate.ddl-auto=update